### ISSUE TITLE
pycharm-community: old versions not removed when upgrading

### ISSUE THREAD

**Issue by benshep** [mkevenaar/chocolatey-packages#70]
## Expected Behavior

When I upgrade packages with `choco upgrade all`, I'd expect old versions of PyCharm to be removed.

## Current Behavior

Old versions of PyCharm still exist on the system after upgrading.

## Steps to Reproduce (for bugs)

1. `choco install pycharm-community --version=2020.2.1`
2. `choco upgrade pycharm-community`

The newest version (2020.2.2) is installed, but 2020.2.1 is *not* uninstalled. I do see a warning message "WARNING: pycharm-community has already been uninstalled by other means", indicating that Chocolatey has detected some problem with the install perhaps? I haven't touched the manual (un)install, and haven't even opened PyCharm at this point.

## Context
It's a mild inconvenience - I have to manually remove old versions each time.

Apologies - I know this is a duplicate of https://github.com/mkevenaar/chocolatey-packages/issues/5, but I didn't get any response on that one.

## Your Environment

* Package Version used: 2020.2.2
* Operating System and version: Windows 10 x64 build 17134
* Chocolatey version: 0.10.15
* Install/uninstall gist: https://gist.github.com/benshep/f97b94b093df6bb80271f5c7c943d6e7

**Comment by aminya** [comment]
I have the same problem! Is there any progress on this?

**Comment by mkevenaar** [comment]
This has been fixed in git. However this will take two new packages (starting from now) before this will work, until then, please uninstall previous versions manually.

Note: the commits have been submitted after the pycharm* package releases for 202.2.3

**Comment by ba-tno** [comment]
> However this will take two new packages (starting from now)

Maybe I'm misunderstanding this sentence, but I just updated to `2020.3` from `2020.2.3` using `cup all -y` and version `2020.2.3` is not removed.  
Looking at the chocolatey [version history](https://chocolatey.org/packages/PyCharm-community#versionhistory) I see that `2020.3` is the third package after `2020.2.3`.
Or is that expected and should an update of `2020.3` result in its removal?

**Comment by mkevenaar** [comment]
@ba-tno did you see anything in the log files regarding multiple found versions, it will only remove one older version to be sure it does not remove too much...

**Comment by ba-tno** [comment]
I did not see anything in the log about multiple found version, I only had `2020.2.3` installed. This is the log exceprt surrounding the pycharm uninstall:

```log
2020-12-10 16:28:43,340 26188 [DEBUG] - ---------------------------Script Execution---------------------------
2020-12-10 16:28:43,347 26188 [DEBUG] - Running 'ChocolateyScriptRunner' for pycharm-community v2020.2.3 with packageScript 'C:\ProgramData\chocolatey\lib\pycharm-community\tools\chocolateyBeforeModify.ps1', packageFolder:'C:\ProgramData\chocolatey\lib\pycharm-community', installArguments: '', packageParameters: '',
2020-12-10 16:28:43,347 26188 [DEBUG] - Running 'C:\ProgramData\chocolatey\lib\pycharm-community\tools\chocolateyBeforeModify.ps1'
2020-12-10 16:28:43,357 26188 [DEBUG] - Running 'Get-UninstallRegistryKey' for 'pycharm-community' with SoftwareName:'JetBrains PyCharm Community Edition*'
2020-12-10 16:28:43,357 26188 [INFO ] - VERBOSE: Retrieving all uninstall registry keys
2020-12-10 16:28:43,637 26188 [DEBUG] - Registry uninstall keys on system: 410
2020-12-10 16:28:43,637 26188 [DEBUG] - Error handling check: 'Get-ItemProperty' fails if a registry key is encoded incorrectly.
2020-12-10 16:28:43,841 26188 [DEBUG] - Found 0 uninstall registry key(s) with SoftwareName:'JetBrains PyCharm Community Edition*'
2020-12-10 16:28:43,841 26188 [WARN ] - WARNING: pycharm-community has already been uninstalled by other means.
2020-12-10 16:28:43,841 26188 [DEBUG] - ----------------------------------------------------------------------
```

I've now uninstalled it manually, so no real issue there, but thought I would indicate that this issue still seems to exist.
Let me know if you need additional logs.

**Comment by mkevenaar** [comment]
@ba-tno based on that output you still had an old version of the `chocolateyBeforeModify.ps1` file installed It should be working on your machine when the next release of pycharm-community is released.
